version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bridge_gym_db
    restart: always
    environment:
      POSTGRES_USER: bridge_user
      POSTGRES_PASSWORD: bridge_password
      POSTGRES_DB: bridge_gym
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
